### ISSUE TITLE
No module named helpers

### ISSUE THREAD

**Issue by YukiSakuma** [dr-costas/mad-twinnet#5]
Downloaded the zip repository, and trying to execute `use_me.py`
Following output gives this
`Traceback (most recent call last):
  File "D:\mad-twinnet-master\mad-twinnet-master\scripts\use_me.py", line 17, in
 <module>
    from helpers.data_feeder import data_feeder_testing, data_process_results_te
sting
ModuleNotFoundError: No module named 'helpers'`

**Comment by dr-costas** [comment]
Hi, 

This is most probably because you have not set up properly your python path. 

If you are using some IDE, then you will have to check the settings of your IDE when running the script. 

If you are running this through the terminal, then you should issue the command `export PYTHONPATH=$PYTHONPATH:.`  or `export PYTHONPATH=$PYTHONPATH:../`, depending from which directory you are executing the `python` command.

**Comment by YukiSakuma** [comment]
Hello thanks for the reply, I am trying to execute it on conda using the command
`py -3.6 PATHtoscript`

**Comment by dr-costas** [comment]
Hi, 

If you are on Linux or MacOS, then go to the project's root directory and issue the commands: 

```
export PYTHONPATH=$PYTHONPATH:.
python scripts/use_me.py
````

If you are on Windows, then replace the "/" with "\\" and check this: https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7

on how to set up properly the python path.

**Comment by YukiSakuma** [comment]
Hello I tried the command if I understood your reply

```
"D:\Anaconda3\python.exe" "D:\mad-twinnet-master\mad-
twinnet-master\scripts\use_me.py"
```
But output is still the same, adding py -3.6 will result invalid command
```
Traceback (most recent call last):
  File "D\mad-twinnet-master\mad-twinnet-master\scripts\use_me.py", line 17, in
 <module>
    from helpers.data_feeder import data_feeder_testing, data_process_results_te
sting
ModuleNotFoundError: No module named 'helpers'
```

**Comment by dr-costas** [comment]
Hi, 

The problem is not of the code but of your system. 

In particular, the problem is that your python does not know where to find the `helpers` module. 

In general, you can let your python to know where to find "things", but including paths in the PYTHONPATH environmental variable. 

Guessing from your messages, you are using Windows. Unfortunately, I do not know how to help you on your OS. That is why I suggested to you to read the question on StackOverflow. 

I guess you can find lots of help if you google "how to set up PYTHONPATH on windows".

Please let me know if you fixed that. 

Cheers!

**Comment by YukiSakuma** [comment]
Oh sorry didn't know the comment was edited (I didn't refresh the page) to include the stackoverflow link, and yes I am using windows, I'll try to read it thanks

**Comment by dr-costas** [comment]
No worries! Try and let me know if everything worked!
